"""empty message

Revision ID: fdec0bf0a7f0
Revises: 
Create Date: 2022-07-19 21:49:53.817153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdec0bf0a7f0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('users', 'flag',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('users', 'last_login',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint(None, 'users', ['password'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'last_login',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'flag',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    # ### end Alembic commands ###
